script:
  bundle exec ruhoh compile
before_deploy:
  git clone https://rguillome:$GITHUB_TOKEN@github.com/rguillome/rguillome.github.io.git $TARGET_DEPLOY_DIR
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh $TRAVIS_BUILD_DIR/compiled $TARGET_DEPLOY_DIR
  on:
    branch: master
